# Generated by Django 3.2.9 on 2021-11-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("date", models.DateField()),
                ("average_temperature", models.FloatField(blank=True, null=True)),
                (
                    "average_temperature_uncertainty",
                    models.FloatField(blank=True, null=True),
                ),
                ("city", models.CharField(max_length=163)),
                ("country", models.CharField(max_length=56)),
                ("latitude", models.CharField(max_length=20)),
                ("longitude", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "global_land_temperatures_by_city",
            },
        ),
    ]
